config/routes.rb
Horschgallery::Application.routes.draw do
  # Routes for the Photo resource:
  # CREATE


  get "/login" => 'sessions#new'
  get "/logout" => 'sessions#destroy'
  post "/sessions" => 'sessions#create'




 root 'photos#index'

  resources :users
  resources :photos
  resources :categories




  post '/search' => 'photos#search'

  # get '/photos/new', controller: 'photos', action: 'new', :as => 'new_photo'
  # post '/photos', controller: 'photos', action: 'create'

  # # READ
  # get '/photos', controller: 'photos', action: 'index'
  # get '/photos/:id', controller: 'photos', action: 'show', :as => 'photo'

  # # UPDATE
  # get '/photos/:id/edit', controller: 'photos', action: 'edit', :as => 'edit_photo'
  # patch '/photos/:id', controller: 'photos', action: 'update'

  # # DELETE
  # delete '/photos/:id', controller: 'photos', action: 'destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/format.rb
class Format < ActiveRecord::Base
end

app/models/frame_style.rb
class FrameStyle < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base


 # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query

    # where("title LIKE ?", "%#{query}%")

# where('title LIKE ? OR prod_id like ?', "%#{search}%", "%#{search}%")

      where('prod_id LIKE ? OR prod_id LIKE ? OR title LIKE ?', "#{query}" ,  "#{query}%wf" , "%#{query}%")


  end

end

app/models/image_category.rb
class ImageCategory < ActiveRecord::Base
end

app/models/image_frame_style.rb
class ImageFrameStyle < ActiveRecord::Base
end

app/models/image_option.rb
class ImageOption < ActiveRecord::Base
end

app/models/mat.rb
class Mat < ActiveRecord::Base
end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/models/user_cart.rb
class UserCart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(:id => params[:id])
    @categories = Category.all
  end

  def new
  end

  def create
    @category = Category.new

    if @category.save
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by(:id => params[:id])
  end

  def update
    @category = Category.find_by(:id => params[:id])

    if @category.save
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find_by(:id => params[:id])
    @category.destroy
    redirect_to categories_url
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Image.all
    @categories = Category.all
  end

  def show
    @photo = Image.find_by(:id => params[:id])
    @photos = Image.all
  end

  def new
  end

  def search

       @photos = Image.search(params[:search]).order(:prod_id)
       @query  = params[:search]
  end

  def create
    @photo = Image.new

    if @photo.save
      redirect_to photos_url
    else
      render 'new'
    end
  end

  def edit
    @photo = Image.find_by(:id => params[:id])
  end

  def update
    @photo = Image.find_by(:id => params[:id])

    if @photo.save
      redirect_to photos_url
    else
      render 'new'
    end
  end

  def destroy
    @photo = Image.find_by(:id => params[:id])
    @photo.destroy
    redirect_to photos_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def destroy
    reset_session
    redirect_to root_url, notice: "See ya!"
  end

  def create
    user = User.find_by(email_address: params[:email_address])
    if user.present?
      if user.authenticate(params[:password])
        # Yay!
        session[:user_id] = user.id
        redirect_to root_url
      else
        redirect_to '/login', notice: "Bad password."
      end
    else
      redirect_to '/login', notice: "User unknown, try again."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :updatge, :destroy]


  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new
    @user.email_address = params[:user][:email_address]
    @user.password = params[:user][:password]
    @user.password_confirmation = @user.password
    @user.firstname = params[:user][:firstname]
    @user.lastname = params[:user][:lastname]

    if @user.save
      UserMailer.welcome(@user).deliver
      format.html { redirect_to root_path, notice: "Thanks for signing up!" }
    else
      render 'new'
    end


  end

  def edit
  end

  def update
    @user.email_address = params[:user][:email_address]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password]
    @user.firstname = params[:user][:firstname]
    @user.lastname = params[:user][:lastname]

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
  end

private

  def set_user
    @user = User.find(params[:id])
  end

   def require_login
    if params[:id] != session[:user_id]
      redirect_to root_url, notice: "Nice try!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
hello

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

Sub Categories

<% @categories.where(main_cat: @category.name).each do |sub_cat| %>
  <h4><%= link_to sub_cat.name, categories_url(id: @category.id) %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Horschgallery</title>



  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">






</head>
<body>


<div class='pagecontainer'>


    <div class='menubar' >
        <div class='logo'><a href='/photos'><img src='/misc/logo.jpg' width='100'></a></div>
        <div class= 'restofmenu'>
            <li><a href="#">Our Story</a></li>
            <li><a href="#">The Photographers</a></li><li><a href="#">Compare Sizes</a></li>
            <li><a href="#">Framing Options</a></li>
            <li><a href="#">Reviews</a></li>
            <li><a href="#">FAQ</a></li>


            <li><a href="#"></a></li>
        </div>
        <div class='account_right-justify'>
              <li><i class="fa fa-shopping-cart"></i><a href="#">Cart</a></li>
               <% if session[:user_id] %>
                  <li><%=  link_to "#{User.find_by(id: session[:user_id]).firstname.titleize} #{User.find_by(id: session[:user_id]).lastname.titleize}", "#" %>|<%= link_to "Sign Out", '/logout' %></li>
                <% else %>
                    <li><i class="fa fa-sign-in"></i><%= link_to "Log In", '/login' %>|<%= link_to "Create Account", '/login' %></li>
                <% end %>
        </div>

    </div>


    <div class='banner'>
      <a href='/photos' ><img  src='/misc/panbw2_crop.jpg' width='1010'/></a>
    </div>





    <div class='promotion' >


      <div class='searchfield'>



          <%= form_tag( '/search', :method => "post") do %>
            <%= text_field_tag :search, params[:search], size: 38, class: "searchbar", placeholder: "  What photo are you looking for?  " %>
             <%= submit_tag "Search", class: "search_button action_button" %>
         <% end %>

      </div>

      <div class= 'promotext'>&nbsp&nbspNOVEMBER SALE.&nbsp&nbspENDS TUESDAY.&nbsp&nbspGET 15% OFF YOUR ORDER. &nbsp<a href="#">*more details</a></div>


    </div>




<%= yield %>



<footer class='footer'>&copy HorschGallery 2013







</footer>

</div>


<style>


</style>



</body>
</html>

app/views/photos/_extra_product_info.html.erb
<div class='extra_product_info container_backdrop'>


      ID# <%= @photo.prod_id %><br>
       <span class='stars'><%= ("&#9733;" * 5).html_safe %></span>&nbsp&nbsp53 customer reviews
      <br>
      Ground Shipping: 3-5 business days
      <br>
      Full Refunds & Free Return Shipping. Always.
      <br />
      <div class="mydivider"> </div>

      Did you know our Chicago photography gallery was located on Michigan Avenue for nearly 20 years?
      <a href="http://www.horschgallery.com/photographer.aspx?__p=%C5%93">Read how we got started</a>
      <br />
      <div class="mydivider"> <br />
      </div>
      <b>Like this photograph?  Share.  Save.  Enjoy.</b>
      <br>
      <img src="/misc/social.jpg"  >

</div>

app/views/photos/_hardsell.html.erb
<div class = "hardsell container_backdrop">

  <h4>3 Reasons To Shop For A Photograph From HorschGallery.com</h4>
  <p><b>We offer a full refund including initial shipping.</b><br>If you aren't happy with your new photo, we'll refund everything. This includes: photo price + tax + initial shipping + free return shipping.</p>
  <p ><b>We feature one-of-a-kind photographs.</b><br>Every Chicago image was photographed and carefully crafted by gallery owner, Bob Horsch.  In contrast, large e-commerce print and poster websites sacrifice quality in order to mass produce.  </p>
  <p ><b>We are a long standing & reputable, local family business.</b><br>Since 1982, we have been selling high quality & affordable photos with two previous stores on Michigan Avenue.</p>


</div>

app/views/photos/_headline.html.erb
<div class='headline container_backdrop' >

    <h1>A Chicago Photograph Lasts Forever</h1>
    <p class='summary'>Over the last 30 years Bob has documented the dynamic life and architecture of Chicago through the lens of a camera.  His photography portfolio contains a diverse selection of Chicago cityscape photos from all four colorful seasons blended with eye-catching pictures of the major Chicago sports teams and their respective home stadiums.</p>

    <p class="summary2">Here you can browse through hundreds of quality & affordable photographs ranging from the early 1900's to the present day.  All of his one-of-a-kind photographs are available in a variety of styles which include vintage, modern, black & white and color prints. </p>

    <p><b>Your memories of Chicago may soften over time, but a photograph of Chicago will preserve every detail.</b></p>

    <p>Thanks for visiting.</p>

    <p class='didyouknow'>Did you know Bob's Chicago photo gallery was on Michigan Ave. for almost 20 years?  <a href="#">Read more his story</a></p>





</div>

app/views/photos/_main_section.html.erb
<div class= 'main'>

<%= render 'navigation_section' %>


<div class='frontpage'>

  <%= render 'headline' %>
  <%= render 'photo_container' %>

</div>


</div>

app/views/photos/_navigation_section.html.erb
<div class='navsection'>

    <div class='navcontainers container_backdrop'>

        <div class='navheader'>Customer Testimonial</div>
        "The photographs are even more stunning in person and the frame is very professional."<br/>
        <b>Cindy, 39 (09/13)</b><br/><a href="#">Read More Reviews</a>

    </div>

    <div class='navcontainers container_backdrop'>

        <div class='navheader'>Photgraphy Portfolio</div>

        <% @categories.where(main_cat: 'main').each do |category| %>

            <div class="list-group-item" id="user"><a class='navlink'  href=<%= category_url(category.id) %>><%= category.name.titleize %></a></div>

        <% end %>

<!--         <div class="list-group-item" id="user"><a class='navlink'  href="#">Top 10 / Best Sellers</a></div>
 -->        <!--     <span id='popup'>
          <div><a class='list-group-item' href="#">Chicago Gifts Top 10</a></div>
          <div><a class='list-group-item' href="#">Top Selling Chicago Sports</a></div>
          <div><a class='list-group-item' href="#">Top Selling Chicago Skyline</a></div>
        </span> -->
    <!--     <div class="list-group-item" id="user"><a class='navlink' href="#">Most Recent Photography</a></div>

        <div class="list-group-item-blank"><a href="#"></a></div>

        <div class="list-group-item"><a class='navlink' href="#">Chicago Black & White</a> </div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Vintage</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Panoramas</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Cityscape</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Aerials</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Landmarks</a></div>

        <div class="list-group-item-blank"><a href="#"></a></div>

        <div class="list-group-item"><a class='navlink' href="#">Chicago Blackhawks</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Bears</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Cubs</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago White Sox</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Chicago Bulls</a></div>

        <div class="list-group-item-blank"><a class='navlink' href="#"></a></div>

        <div class="list-group-item"><a class='navlink' href="#">New York Yankees</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Other Sports Stadiums</a></div>

        <div class="list-group-item-blank"><a class='navlink' href="#"></a></div>

        <div class="list-group-item"><a class='navlink' href="#">Notre Dame Football</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Big 10 College Football</a></div>
        <div class="list-group-item"><a class='navlink' href="#">European Cities</a></div>

        <div class="list-group-item-blank"><a class='navlink' href="#"></a></div>

        <div class="list-group-item"><a class='navlink' href="#">San Francisco, California</a></div>
        <div class="list-group-item"><a class='navlink' href="#">Boston, Massachusetts</a></div>

        <div class="list-group-item-blank"><a class='navlink' href="#"></a></div>

        <div class="list-group-item-last"><a class='navlink' href="#">Nature Photography</a></div> -->

    </div>

</div>

app/views/photos/_photo_container.html.erb
<div class='photocontainer'>
  <% @photos.where.not(homepage_rank: 0).order(:homepage_rank).each do |photo| %>
    <div class='photo container_backdrop'>
    <a href= <%= photo_url(photo.id) %>><img src= <%= photo.image_url %> width= "230px">  </a>
    <figcaption class="photo_thumb_title"><%= link_to photo.title, photo_url(photo.id) %><br/><%= photo.main_cat.titleize %></figcaption>
    </div>
  <% end %>
</div>

app/views/photos/_photo_description.html.erb
<% if @photo.desc != nil %>

    <div class= 'photo_description container_backdrop'>


      <p class='quote'> <%= @photo.desc %>
      &nbsp&nbsp<b>~Bob Horsch</b>
      </p>


    </div>

<% end %>

app/views/photos/_photo_ribbon.html.erb
<div class="ribbon container_backdrop"><h4>Customers Also Viewed</h4>
  <% @photos.where(sub_cat: "#{@photo.sub_cat.downcase}").shuffle.take(8).each do |photo| %>
    <%= link_to image_tag(photo.image_url, class: "poster-container"), photo_url(photo.id) %>
  <% end %>
</div>

app/views/photos/_product_info.html.erb
<div class='product_info container_backdrop'>



    <div class='photo_options'>

    <table>
        <tbody>
            <tr>
              <td><b><%= label_tag 'choose-photo_size', 'Choose Your Size:'  %></b></td>
              <td> <%= select_tag 'choose-size', "<option>8x10 Photo Only</option><option>8x10 Photo w/ 11x14 Mat</option><option>8x10 Photo w/ 11x14 Mat - Framed</option>".html_safe %></td>
            </tr>
            <tr>
              <td><%= label_tag 'choose_mat', 'Mat Color:' %></td>
              <td><%= select_tag 'choose_mat', "<option>Fog / Black</option><option>Bright White</option>".html_safe %></td>
            </tr>
            <tr>
              <td><%= label_tag 'choose_frame', 'Frame Style:' %></td>
              <td><%= select_tag 'choose_frame', "<option>Classic Black - Thin Rounded</option><option>Classic Black - Wide Flat</option>".html_safe %></td>
            </tr>
            <tr>
              <td >Price:</td>
              <td class='pricecolor'>$<%= @photo.price %></td>
            </tr>
            <tr>
              <td><%= label_tag 'qty', 'Quantity:' %></td>
              <td><%= select_tag 'qty', "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe %></td>
            </tr>

        </tbody>
    </table>

    <br>

    <div>
    <a href="#" class="cart_button action_button">Add To Cart</a>
    <a href="/login" class="fav_button"><i class="fa fa-heart"></i></a>
    </div>

</div>




</div> <!-- 'product_info' -->

app/views/photos/_showcase_product.html.erb
<div class='breadcrumbs'>
   <a href='/photos'>Home</a> >
   <a href='#'><%= @photo.main_cat.titleize %></a> >
  <a href='#'><%= @photo.sub_cat.titleize %></a>
</div>

<div class ='showcase container_backdrop'>
  <h1 class='prodtitle'><strong><%= @photo.title %></strong></h1>
<!--
<a class="test-popup-link" href="<%= @photo.image_url %>">
  <img id="myphoto" src="<%= @photo.image_url %>" width='500'>
</a>
 -->

<a href="<%= @photo.image_url %>" class='image-link' ><img id="myphoto" src="<%= @photo.image_url %>" width='500'>
</a>







  <br>

  <div class='zoom'>
    <li class='zoombutton'><a href=<%= photo_url(@photo.id-1) %>>PREV</a></li>
    <li class='zoombutton'><a href="<%= @photo.image_url %>" class='image-link'>ZOOM</a></li>
    <li class='zoombutton'><a href=<%= photo_url(@photo.id+1) %>>NEXT</a></li>
  </div>
</div>


<!-- // $(document).ready(function() {
//   $('.test-popup-link').magnificPopup({type:'image'});
// });
 -->

app/views/photos/edit.html.erb
<h1>Editing Photo #<%= @photo.id %></h1>


<%= form_tag(photo_url(@photo), method: 'patch') do %>


  <div>
    <%= submit_tag "Update Photo" %>
  </div>

<% end %>

app/views/photos/new.html.erb
<h1>New Photo</h1>


<%= form_tag(photos_url, method: 'post') do %>



  <div>
    <%= submit_tag "Create Photo" %>
  </div>
<% end %>

app/views/photos/search.html.erb
<div class= 'main'>

<%= render 'navigation_section' %>


  <div class='frontpage'>

    <%  if @query.blank? %>

       <h4 class='search_title_zero'>Whoops.&nbsp&nbspYou didn't enter any keywords in the search bar.  Please try again.</h4>

     <%  elsif @photos.count == 0 %>

        <h4 class='search_title_zero'>Whoops.&nbsp&nbspWe didn't find any photographs that matched your search.&nbsp&nbspPlease check the spelling or try again.</h4>

    <% else %>

      <h4 class='search_title'>Awesome!&nbsp&nbspWe found <%= pluralize(@photos.count,'photograph') %> that matched your keywords.</h4>

          <div class='photocontainer'>

        <% @photos.take(12).each do |photo| %>
           <div class='photo container_backdrop'>
            <a href= <%= photo_url(photo.id) %>><img src= <%= photo.image_url  %> width= "230">  </a>
            <figcaption class="photo_thumb_title"><%= link_to photo.title, photo_url(photo.id) %><br/><%= photo.main_cat.titleize %></figcaption>
          </div>

    <% end %>

    </div>

    <% end %>




  </div>


</div>

app/views/photos/show.html.erb
<div class='main'>


  <%= render 'showcase_product' %>
  <%= render 'product_info' %>
  <%= render 'extra_product_info' %>



<%= render 'photo_description' %>
<%= render 'photo_ribbon' %>


<%= render 'hardsell' %>

app/views/users/_form.html.erb
  <%= form_for @user do |f| %>

<table>
  <tbody>
  <tr>
    <td><%= f.label :firstname, "First Name:" %></td>
    <td><%= f.text_field :firstname ,size: 30 %></td>
  </tr>
  <tr>
    <td><%= f.label :lastname, "Last Name:" %></td>
    <td><%= f.text_field :lastname ,size: 30 %></td>
  </tr>
  <tr>
    <td><%= f.label :email_address, "Email Address:" %></td>
    <td><%= f.text_field :email_address ,size: 30 %></td>
  </tr>
  <tr>
  <td><%= f.label :password,  "Password:"%></td>
  <td><%= f.text_field :password ,size: 30 %></td>
  </tr>

</tbody>
</table>

  <%= f.submit class:"submit_button action_button" %>

  <% end %>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email_address %></td>
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
      <td><%= user.password %></td>

      <td><%= link_to 'Show', user_url(user.id) %></td>
      <td><%= link_to 'Edit', edit_user_url(user.id) %></td>
      <td><%= link_to 'Destroy', user_url(user.id), method: 'delete' %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class='container_backdrop'>

<h4>Create An Account</h4>
<%= render 'form' %>

</div>

app/views/users/show.html.erb
<h1> <%= @user.firstname.titleize %>'s Profile</h1>



<p>
  <b>Email</b>
  <%= @user.email_address %>
</p>


<p>
  <b>First Name:</b>
  <%= @user.firstname%>
</p>

<p>
  <b>Last Name:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>